FROM nvidia/cuda:11.3.1-cudnn8-runtime as base

RUN apt update && apt install -y python3.8 python3-pip

COPY . ./transformer-text-encoder/
WORKDIR ./transformer-text-encoder

RUN pip install .

FROM base
RUN pip install -r tests/requirements.txt
# Weird bug on GPU when executing tests in multiple folders
RUN pytest -s -v tests/unit
RUN pytest -s -v tests/integration

FROM base
ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]